In [1]:
#DIFFERENT DATASETS

file = open("./1000/queryA/queryA_1000.txt","r") 

# QUERY A (#1000) Overall
print "QUERY A (#1000): OVERALL\n"

# overall
split_tag = "i2b2 query&quot;:"

with file as f:
    for line in f:
        cnt = ''.join(line).split(split_tag)
        if len(cnt)>1:
            print ''.join(cnt[1]).split(",")[0]
            
file.close()

QUERY A (#1000): OVERALL

7077
6745
7324
6849
6930
6794
7033
6812
6975
7309
6717
6579
7198
6687
7165
6660
8129
7023
8196
6906
6994
6723
8759
6935
8506
7159
6854
10049
6493
6979

In [2]:
#DIFFERENT DATASETS

file = open("./1000/queryB/queryB_1000.txt","r") 

# QUERY B (#1000) Overall
print "QUERY B (#1000): OVERALL\n"

# overall
split_tag = "i2b2 query&quot;:"

with file as f:
    for line in f:
        cnt = ''.join(line).split(split_tag)
        if len(cnt)>1:
            print ''.join(cnt[1]).split(",")[0]
            
file.close()

QUERY B (#1000): OVERALL

20963
19547
18678
20801
19154
19348
20299
19208
19243
18768
18864
18994
18809
20779
18984
21127
19301
18823
19219
19402
20598
20892
19471
19065
20470
19022
19677
19233
20344
19246

In [3]:
#DIFFERENT DATASETS

file = open("./2000/queryA/queryA_2000.txt","r") 

# QUERY A (#2000) Overall
print "QUERY A (#2000): OVERALL\n"

# overall
split_tag = "i2b2 query&quot;:"

with file as f:
    for line in f:
        cnt = ''.join(line).split(split_tag)
        if len(cnt)>1:
            print ''.join(cnt[1]).split(",")[0]
            
file.close()

QUERY A (#2000): OVERALL

9496
9643
9619
9486
9551
8825
9616
8881
8885
9352
9122
9395
9113
8792
8982
8902
9621
9055
8876
9869
9080
9390
9023
9318
8636
9111
10022
8793
9268
9430

In [4]:
#DIFFERENT DATASETS

file = open("./2000/queryB/queryB_2000.txt","r") 

# QUERY B (#2000) Overall
print "QUERY B (#2000): OVERALL\n"

# overall
split_tag = "i2b2 query&quot;:"

with file as f:
    for line in f:
        cnt = ''.join(line).split(split_tag)
        if len(cnt)>1:
            print ''.join(cnt[1]).split(",")[0]
            
file.close()

QUERY B (#2000): OVERALL

27258
26528
25982
26542
25350
26339
26172
25867
27567
25667
26829
25321
25557
27456
26417
26899
27444
25804
25003
26314
25962
27270
24853
26189
26481
25797
25460
26232
27073
24993

In [5]:
#DIFFERENT DATASETS

file = open("./4000/queryA/queryA_4000.txt","r") 

# QUERY A (#4000) Overall
print "QUERY A (#4000): OVERALL\n"

# overall
split_tag = "i2b2 query&quot;:"

with file as f:
    for line in f:
        cnt = ''.join(line).split(split_tag)
        if len(cnt)>1:
            print ''.join(cnt[1]).split(",")[0]
            
file.close()

QUERY A (#4000): OVERALL

13999
13783
13513
13435
13805
13254
12950
13197
12848
13046
12796
12858
13482
12567
12410
12520
12437
12861
13013
13832
12631
12549
12771
12337
13120
12490
12554
12359
12455
12565

In [6]:
#DIFFERENT DATASETS

file = open("./4000/queryB/queryB_4000.txt","r") 

# QUERY B (#4000) Overall
print "QUERY B (#4000): OVERALL\n"

# overall
split_tag = "i2b2 query&quot;:"

with file as f:
    for line in f:
        cnt = ''.join(line).split(split_tag)
        if len(cnt)>1:
            print ''.join(cnt[1]).split(",")[0]
            
file.close()

QUERY B (#4000): OVERALL

36546
35532
35424
34939
36851
35171
35678
35659
36932
35754
36910
34809
36239
35210
35832
36800
35468
35741
36073
35749
36887
35642
35550
37005
36647
35723
35844
35825
36077
36544

In [7]:
#DIFFERENT DATASETS

file = open("./normal/queryA/queryA_full.txt","r") 

# QUERY A (normal) Overall
print "QUERY A (normal): OVERALL\n"

# overall
split_tag = "i2b2 query&quot;:"

with file as f:
    for line in f:
        cnt = ''.join(line).split(split_tag)
        if len(cnt)>1:
            print ''.join(cnt[1]).split(",")[0]
            
file.close()

QUERY A (normal): OVERALL

22100
24000
23715
21058
21200
20476
20124
19825
20073
21596
22221
21961
18850
21057
19545
19627
19654
19419
19671
23066
19238
19179
18926
18231
20926
19630
19161
19220
23024
19459

In [8]:
#DIFFERENT DATASETS

file = open("./normal/queryB/queryB_full.txt","r") 

# QUERY B (normal) Overall
print "QUERY B (normal): OVERALL\n"

# overall
split_tag = "i2b2 query&quot;:"

with file as f:
    for line in f:
        cnt = ''.join(line).split(split_tag)
        if len(cnt)>1:
            print ''.join(cnt[1]).split(",")[0]
            
file.close()

QUERY B (normal): OVERALL

56842
55113
52833
57401
56151
53373
53360
59119
54890
54648
55281
55566
54521
54724
53680
56375
54493
59374
55960
58994
55214
55744
54868
54892
55542
54699
58189
58477
55218
57879